version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      #- "8080:80"
      - "443:443" #expose port 443
    restart: on-failure
  
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "3306"
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file: .env
    expose:
      - "9000"
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'home/login/data/wordpress'
  
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'home/login/data/mariadb'

networks:
  inception:
    driver: bridge  #tells docker to automatically install rules that will allow 3 containers communicate in a bridge